version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - static
    volumes_from:
      - static:ro
  static:
    image: busybox
    volumes:
      - ./static:/usr/share/nginx/html
